FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY command_center /command_center

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /command_center
#USER appuser

WORKDIR /command_center
ENV FLASK_DEBUG=1
CMD ["python", "center.py"]

EXPOSE 6069
