FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY defence_system /defence_system

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /defence_system
#USER appuser

WORKDIR /defence_system
CMD ["python", "system.py"]

EXPOSE 6068